version: '3'

services:

  my-database:
    image: 'postgres:13'
    container_name: 'MyDBContainer'
    environment:
      - 'POSTGRES_USER=sa'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=myDB'

  my-web:
    build: ./
    image: 'fillswim/shop'
    container_name: 'MyAppContainer'
    ports:
      - "8080:8080"
    depends_on:
      - my-database